apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: osos3/product:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
