apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob1
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: count1
              image: nginx
              command: ["echo", "Hello from CronJob"]
          restartPolicy: Never