apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test
spec:
  replicas: 3
  selector: 
     matchLabels:
       env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
       - name: nginx
         image: osos3/web-test:latest
         ports:
           - containerPort: 8080
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - node1
                      



