apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test2
spec:
  replicas: 3
  selector: 
     matchLabels:
       env: prod
  # strategy:
  #   type: Recreate
    # rollingUpdate:
    #   maxSurge: 1
    #   maxUnavailable: 1
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
       - name: nginx
         image: osos3/web-test:latest
         ports:
           - containerPort: 8080
      # tolerations:
      #   - key: "name"
      #     operator: "Equal"
      #     value: "sallam"
      #     effect: "PreferNoSchedule"
         #image: img-test
         #imagePullPolicy: Never

