apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: ds
spec:
   selector:
     matchLabels:
       env: prod
   template:
     metadata:
       labels:
         env: prod
     spec:
      containers:
         - name: count2
           image: nginx
       
