apiVersion: batch/v1
kind: Job
metadata:
  name: job1
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
        - name: count1
          image: nginx
          command: ["echo", "Hello from Job"]
      restartPolicy: Never