apiVersion: v1 
kind: Pod
metadata: 
  name: nginx3
  labels:
    env: prod
spec: 
  containers:
    - name: nginx
      image: vish/stress
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      
         

        
         
  # tolerations:
  #   - key: "name"
  #     operator: "Equal"
  #     value: "osos"
  #     effect: "NoSchedule"