apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  replicas: 3
  selector: 
     matchLabels:
       env: prod

  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
       - name: ubuntu
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo $(date -u) >> /data/output.txt; sleep 20; done"]
         volumeMounts:
          - mountPath: "/data"
            name: test-pod
      volumes:
         - name: test-pod
           persistentVolumeClaim:
           claimName: pvc-tets
 

