apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: rs
spec:
   replicas: 2
   selector:
     matchLabels:
       env: prod
   template:
     metadata:
       labels:
         env: prod
     spec:
      containers:
         - name: count2
           image: nginx
       
