apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deploy
  namespace: mongo-express
spec:
  replicas: 1
  selector: 
     matchLabels:
       env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
       - name: express
         image: mongo-express:latest
         ports:
            - containerPort: 8081
         envFrom:
          - configMapRef:
              name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
  namespace: mongo-express
spec:
  type: NodePort
  selector:
    env: prod
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30002

