apiVersion: apps/v1
kind: Deployment
metadata:
  name: sim-web-fe-app
  namespace: fe
spec:
  replicas: 2
  selector: 
     matchLabels:
       env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
       - name: nginx
         image: nginx
         volumeMounts:
           - name: empty-dir-volume
             mountPath: /usr/share/nginx/html
      volumes:
        - name: empty-dir-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sim-web-fe-svc
  namespace: fe
spec:
  type: NodePort
  selector:
    env: prod
  ports:
    - port: 8080 
      targetPort: 80
      nodePort: 30001

