apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: hostpath-container
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo $(date -u) >> /data/output.txt; sleep 10; done"]
      volumeMounts:
        - name: hostpath-volume
          mountPath: /data
  volumes:
    - name: hostpath-volume
      hostPath:
        path: /home/sallam/data
        type: DirectoryOrCreate



# To create the pod, use the command:
# spec:
#   containers:
#     - name: centos
#       image: centos
#       command: ["/bin/bash", "-c", "while true; do echo 'Hello from HostPath' > /usr/share/nginx/html/index.html; sleep 10; done"]