apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefull-mysql
spec:
  serviceName: "mysql-svc"  # this is the headless service
  replicas: 2
  selector:
    matchLabels:
     app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb:10.6
          ports:
           - containerPort: 3306
          # envFrom:
          #  - secretRef:
          #      name: mysql-secret
          env:
           - name: MYSQL_ROOT_PASSWORD
             value: "rootpassword"
          volumeMounts:
           - name: mysql-data
             mountPath: /var/lib/mysql
           - name: mysql-init
             mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-init
        configMap:
          name: mysql-config
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
