apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: centos
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo $(date -u) >> /data/output.txt; sleep 20; done"]
      volumeMounts:
        - name: test
          mountPath: /data
  volumes:
    - name: test
      persistentVolumeClaim:
        claimName: pvc