apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test2
spec:
  replicas: 3
  selector: 
     matchLabels:
       env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
       - name: nginx
         image: nginx
         ports:
           - containerPort: 8080
      tolerations:
      - key: "key1"
        operator: "Equal"
        value: "value1"
        effect: "NoSchedule"

